// SPDX-FileCopyrightText: 2026 TKMD and Reftrix Contributors
// SPDX-License-Identifier: AGPL-3.0-only

/**
 * preference MCPツール Zodスキーマ定義
 * ユーザー嗜好プロファイリング用バリデーション
 *
 * Schemas:
 * - preferenceHearInputSchema (モードA: サンプル提示 / モードB: フィードバック受信)
 * - preferenceGetInputSchema (プロファイル取得)
 * - preferenceResetInputSchema (プロファイルリセット)
 *
 * @module tools/preference/schemas
 */

import { z } from "zod";

// ============================================================================
// Error Codes / エラーコード
// ============================================================================

/**
 * preference MCPエラーコード
 * preference MCP error codes
 */
export const PREFERENCE_MCP_ERROR_CODES = {
  /** 入力バリデーションエラー / Input validation error */
  VALIDATION_ERROR: "VALIDATION_ERROR",
  /** サービス未設定 / Service not available */
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  /** プロファイル未検出 / Profile not found */
  PROFILE_NOT_FOUND: "PROFILE_NOT_FOUND",
  /** Embedding生成失敗 / Embedding generation failed */
  EMBEDDING_FAILED: "EMBEDDING_FAILED",
  /** 内部エラー / Internal error */
  INTERNAL_ERROR: "INTERNAL_ERROR",
  /** リセット未確認 / Reset not confirmed */
  RESET_NOT_CONFIRMED: "RESET_NOT_CONFIRMED",
} as const;

export type PreferenceMcpErrorCode =
  (typeof PREFERENCE_MCP_ERROR_CODES)[keyof typeof PREFERENCE_MCP_ERROR_CODES];

/**
 * エラーコードからユーザー向けメッセージに変換（DB構造詳細を隠蔽）
 * Convert error code to user-facing message (hide DB structure details)
 *
 * @param errorCode - エラーコード / Error code
 * @returns サニタイズ済みメッセージ / Sanitized message
 */
export function sanitizeErrorMessage(errorCode: string): string {
  const messages: Record<string, string> = {
    [PREFERENCE_MCP_ERROR_CODES.VALIDATION_ERROR]: "Input validation failed",
    [PREFERENCE_MCP_ERROR_CODES.PROFILE_NOT_FOUND]: "Profile not found",
    [PREFERENCE_MCP_ERROR_CODES.EMBEDDING_FAILED]: "Embedding generation failed",
    [PREFERENCE_MCP_ERROR_CODES.SERVICE_UNAVAILABLE]: "Preference service is not available",
    [PREFERENCE_MCP_ERROR_CODES.INTERNAL_ERROR]: "An internal error occurred",
    [PREFERENCE_MCP_ERROR_CODES.RESET_NOT_CONFIRMED]: "Reset not confirmed",
  };
  return messages[errorCode] ?? "An unexpected error occurred";
}

// ============================================================================
// Feedback Schema / フィードバックスキーマ
// ============================================================================

/**
 * フィードバック評価値
 * Feedback rating values
 */
export const feedbackRatingSchema = z.enum(["positive", "negative", "neutral"]);
export type FeedbackRating = z.infer<typeof feedbackRatingSchema>;

/**
 * 個別フィードバック項目
 * Individual feedback item
 */
export const feedbackItemSchema = z.object({
  /** サンプルID / Sample ID */
  sample_id: z.string().uuid(),
  /** 評価 / Rating */
  rating: feedbackRatingSchema,
  /** コメント（最大500文字） / Comment (max 500 characters) */
  comment: z.string().max(500).optional(),
});

export type FeedbackItem = z.infer<typeof feedbackItemSchema>;

// ============================================================================
// Input Schemas / 入力スキーマ
// ============================================================================

/**
 * preference.hear 入力スキーマ
 * モードA: feedback なし → サンプル提示
 * モードB: feedback あり → フィードバック受信
 *
 * preference.hear input schema
 * Mode A: no feedback → present samples
 * Mode B: feedback present → receive feedback
 */
export const preferenceHearInputSchema = z.object({
  /** プロファイルID（省略時は新規作成） / Profile ID (create new if omitted) */
  profile_id: z.string().uuid().optional(),
  /** フィードバック配列（存在する場合はモードB） / Feedback array (Mode B if present) */
  feedback: z.array(feedbackItemSchema).max(50).optional(),
  /** 嗜好テキスト（Claudeエージェントが生成、10-1000文字） / Preference text (generated by Claude agent, 10-1000 chars) */
  preference_text: z.string().min(10).max(1000).optional(),
  /** 返却サンプル数（デフォルト1件） / Number of samples to return (default 1) */
  limit: z.number().int().min(1).max(10).default(1).optional(),
  /** スキップ数 / Number of samples to skip */
  offset: z.number().int().min(0).max(1000).default(0).optional(),
  /** 除外するサンプルID配列（既評価済み） / Sample IDs to exclude (already evaluated) */
  exclude_ids: z.array(z.string().uuid()).max(50).optional(),
});

export type PreferenceHearInput = z.infer<typeof preferenceHearInputSchema>;

/**
 * preference.get 入力スキーマ
 * preference.get input schema
 */
export const preferenceGetInputSchema = z.object({
  /** プロファイルID（省略時はデフォルト） / Profile ID (default if omitted) */
  profile_id: z.string().uuid().optional(),
  /** シグナルを含める（GDPRデータポータビリティ対応） / Include signals (GDPR data portability) */
  include_signals: z.boolean().optional(),
});

export type PreferenceGetInput = z.infer<typeof preferenceGetInputSchema>;

/**
 * preference.reset 入力スキーマ
 * preference.reset input schema
 */
export const preferenceResetInputSchema = z.object({
  /** プロファイルID（必須） / Profile ID (required) */
  profile_id: z.string().uuid(),
  /** リセット確認フラグ（必須） / Reset confirmation flag (required) */
  confirm: z.boolean(),
  /** 完全削除フラグ（GDPR忘れられる権利対応） / Hard delete flag (GDPR Right to Erasure) */
  hard_delete: z.boolean().optional(),
});

export type PreferenceResetInput = z.infer<typeof preferenceResetInputSchema>;

// ============================================================================
// PII Truncation Utility / PII切り詰めユーティリティ
// ============================================================================

/**
 * IDをログ出力用にtruncateする（PII配慮）
 * Truncate ID for log output (PII consideration)
 *
 * @param id - 対象ID / Target ID
 * @returns truncate済みID / Truncated ID
 */
export function truncateId(id: string | undefined): string {
  if (!id) return "undefined";
  return id.length > 8 ? id.slice(0, 8) + "..." : id;
}
