// SPDX-FileCopyrightText: 2025-2026 Reftrix Contributors
// SPDX-License-Identifier: AGPL-3.0-only

/**
 * Crash Report Sanitizer — PII-safe normalization of Node.js `process.report`
 *
 * Wave 3 PR3a (Plan v3 T2 V1 §4.3 + Δ2 + Δ9). Sanitises raw diagnostic
 * reports emitted by `process.report` (Node.js 20+ built-in) before they are
 * persisted to public disk. Removes:
 *
 * 1. **Sensitive environment variables** (`AUDIT_SENSITIVE_KEYS` SSOT import
 *    from `audit-log.service.ts`) — `DATABASE_URL`, `REDIS_PASSWORD`, etc. →
 *    `[REDACTED]`
 * 2. **argv URLs** (https?:// → `[REDACTED-URL]`)
 * 3. **argv UUIDv4/v7 boot tokens** → `[REDACTED-UUID]`
 * 4. **JS stack frame file paths** outside the repo root →
 *    `[REDACTED-NON-REPO-PATH]`; repo-internal paths normalised to relative
 * 5. **Heap string fields containing `postgres://` / `redis://` URLs** → URL
 *    stripped (CWE-209 + GDPR Art.30)
 * 6. **Native stack non-public symbols** (`__libc_*` / `vips_internal_*`) →
 *    `[REDACTED-NATIVE-INTERNAL]` per Δ9 LCC + SEC sign-off
 *
 * **Fail-open contract** (Δ2 #6): if sanitisation throws, emit a
 * `[SLO_MARKER] crash_report_sanitize_failed` log line and return the
 * original report with `sanitizationApplied=false`. The audit emit downstream
 * triggers L1.5 SLO_MARKER and L3 CRIT (GDPR Art.33 escalate gate via Δ5
 * Metric A — `sanitizationApplied=false` events / 60-min window ≥ 1).
 *
 * **SSOT contract** (V1 §4.3 Δ2): MUST import all 3 symbols from
 * `audit-log.service.ts` — `AUDIT_LOG_CONSTANTS.TARGET_ID_TRUNCATE_LENGTH` /
 * `AUDIT_SENSITIVE_KEYS` / `truncateAuditTargetId`. The
 * INV-AUDIT-EMIT-SSOT-IMPORT-001 AST scan asserts this import path.
 *
 * **Hard prohibitions** (V1 §4.3 forbidden patterns):
 *   - `.slice(0, 8) + "..."` hardcoded literal
 *   - private re-declaration of `SENSITIVE_KEYS`
 *   - any non-imported truncation length constant
 *
 * @module services/crash-report-sanitizer
 * @see Plan v3 T2 V1 §4.3 / Δ2 / Δ9 / §13.1 SEC sign-off evidence #2
 * @see ADR-0021 §"Privacy Considerations" / §"Native Stack Symbol Stripping"
 * @see INV-WORKER-CRASH-DUMP-001 PII-leak-fail-closed standing regression
 * @see INV-AUDIT-EMIT-SSOT-IMPORT-001 SSOT binding standing regression
 */

import * as path from "node:path";
import { logger } from "../utils/logger";
import {
  AUDIT_LOG_CONSTANTS,
  AUDIT_SENSITIVE_KEYS,
  truncateAuditTargetId,
} from "./audit-log.service";

// ============================================================================
// Re-export SSOT symbols for downstream consumers (preserves single import path
// and keeps the INV-AUDIT-EMIT-SSOT-IMPORT-001 AST scan binding stable).
// ============================================================================

export { AUDIT_LOG_CONSTANTS, AUDIT_SENSITIVE_KEYS, truncateAuditTargetId };

// ============================================================================
// Redaction tokens — fixed strings (PII-safe by construction)
// ============================================================================

export const REDACTED_VALUE = "[REDACTED]";
export const REDACTED_URL = "[REDACTED-URL]";
export const REDACTED_UUID = "[REDACTED-UUID]";
export const REDACTED_NON_REPO_PATH = "[REDACTED-NON-REPO-PATH]";
export const REDACTED_NATIVE_INTERNAL = "[REDACTED-NATIVE-INTERNAL]";

/** SLO marker emitted on fail-open path (Δ2 #6 + Δ5 Metric A trigger). */
export const SLO_MARKER_SANITIZE_FAILED = "[SLO_MARKER] crash_report_sanitize_failed";

// ============================================================================
// Regex sources (compiled lazily; readonly at module level)
// ============================================================================

/** Match http:// or https:// URLs (used for argv + heap string redaction). */
const URL_REGEX = /https?:\/\/[^\s"']+/g;

/**
 * Match canonical UUID v4 / v7 forms (8-4-4-4-12 hex, optional version
 * specifier in the 3rd group). Boot tokens generated by `randomUUID()` are
 * v4; per-type tokens generated by internal / Reftrix are typically v7. Both
 * MUST be redacted before public disk write per SEC-V11-01 Rule 6 (boot token
 * log prohibition extended to crash dump body).
 */
const UUID_REGEX = /\b[0-9a-f]{8}-[0-9a-f]{4}-[1-7][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\b/gi;

/**
 * Match DB / cache connection URLs (postgres://, redis://, mongodb://, etc.)
 * embedded in arbitrary string fields. Heap snapshots from `process.report`
 * may contain serialised connection strings; CWE-209 + GDPR Art.30 require
 * stripping before retention.
 */
const CONNECTION_URL_REGEX =
  /\b(?:postgres|postgresql|redis|rediss|mongodb|mongodb\+srv|mysql|amqp|amqps):\/\/[^\s"']+/gi;

/**
 * Match non-public native symbols (libc internals + vips internals). The
 * V1 spec Δ9 contract: replace `__libc_*` / `vips_internal_*` with
 * `[REDACTED-NATIVE-INTERNAL]`. Public APIs (`ONNXSession.run`, `abort`,
 * `Sharp::pipeline`) are preserved as-is.
 */
const NATIVE_INTERNAL_PREFIX_REGEX = /^(?:__libc_|vips_internal_)/;

// ============================================================================
// Repo-root detection (used for JS stack frame normalisation)
// ============================================================================

/**
 * Resolve the repository root for path normalisation. Cached at first call.
 * Defaults to `process.cwd()` if `REFTRIX_REPO_ROOT` env var is unset (test
 * harnesses may override via env to assert deterministic relative paths).
 */
let cachedRepoRoot: string | null = null;
function resolveRepoRoot(): string {
  if (cachedRepoRoot !== null) return cachedRepoRoot;
  const envRoot = process.env.REFTRIX_REPO_ROOT;
  cachedRepoRoot = envRoot && envRoot.length > 0 ? path.resolve(envRoot) : process.cwd();
  return cachedRepoRoot;
}

/** Test-only: reset cached repo root so a different env value can take effect. */
export function resetRepoRootCacheForTesting(): void {
  cachedRepoRoot = null;
}

// ============================================================================
// Sanitisation result shape
// ============================================================================

/**
 * Result of {@link sanitizeReport}. `sanitizationApplied=true` indicates the
 * happy path; `false` indicates a sanitiser exception triggered the fail-open
 * fallback (SLO marker + audit emit Δ2 #6 + Δ5 Metric A).
 */
export interface CrashReportSanitizationResult {
  report: unknown;
  sanitizationApplied: boolean;
  sanitizationDurationMs: number;
  /** Top JS frame summary (sanitised), useful for audit emit. */
  jsStackTopFrame: string | null;
  /** Top native frame symbol (after Δ9 stripping), useful for audit emit. */
  nativeStackTopSymbol: string | null;
}

// ============================================================================
// Core sanitisation helpers (pure functions, deterministic)
// ============================================================================

/**
 * Strip non-public native symbols (`__libc_*` / `vips_internal_*`) per V1 Δ9.
 * Public APIs are preserved. Returns the original symbol if not internal.
 *
 * @example
 *   stripNonPublicNativeSymbols("__libc_malloc") === "[REDACTED-NATIVE-INTERNAL]"
 *   stripNonPublicNativeSymbols("vips_internal_buffer") === "[REDACTED-NATIVE-INTERNAL]"
 *   stripNonPublicNativeSymbols("ONNXSession::Run") === "ONNXSession::Run"
 */
export function stripNonPublicNativeSymbols(symbol: string): string {
  if (typeof symbol !== "string" || symbol.length === 0) return symbol;
  if (NATIVE_INTERNAL_PREFIX_REGEX.test(symbol)) {
    return REDACTED_NATIVE_INTERNAL;
  }
  return symbol;
}

/**
 * Sanitise an argv element: redact URLs, UUIDs, and otherwise pass-through.
 * Used by {@link sanitizeArgv}.
 */
export function sanitizeArgvElement(arg: string): string {
  if (typeof arg !== "string" || arg.length === 0) return arg;
  // Order matters: URL first (it may contain a UUID), then UUID, then keep.
  let result = arg;
  if (URL_REGEX.test(result)) {
    URL_REGEX.lastIndex = 0;
    result = result.replace(URL_REGEX, REDACTED_URL);
  }
  if (UUID_REGEX.test(result)) {
    UUID_REGEX.lastIndex = 0;
    result = result.replace(UUID_REGEX, REDACTED_UUID);
  }
  return result;
}

/**
 * Sanitise the argv array. Returns a new array; does not mutate input.
 *
 * Per V1 §7.1 unit test #1 + Δ2 #2 / #3:
 *   - `https://example.com/page` → `[REDACTED-URL]`
 *   - UUIDv4/v7 boot token → `[REDACTED-UUID]`
 *   - `--page` / `--backfill` CLI flags preserved
 */
export function sanitizeArgv(argv: readonly string[]): string[] {
  if (!Array.isArray(argv)) return [];
  return argv.map(sanitizeArgvElement);
}

/**
 * Sanitise the environment variables object. Returns a new object; does not
 * mutate input. Per V1 §4.3 SSOT pattern — uses `AUDIT_SENSITIVE_KEYS` from
 * the audit-log SSOT directly (V1 §4.3 forbidden patterns: private
 * re-declaration would fail INV-AUDIT-EMIT-SSOT-IMPORT-001 AST scan).
 *
 * Per V1 §7.1 unit test #2 + Δ2 #1:
 *   - `DATABASE_URL` / `REDIS_PASSWORD` / `OPENAI_API_KEY` → `[REDACTED]`
 *     (matched against `AUDIT_SENSITIVE_KEYS` set, case-insensitive
 *     substring per the existing `audit-log.service` semantics — keys
 *     literally containing `password`/`token`/`secret`/`apiKey`/etc.)
 *   - Reftrix `NODE_ENV` / `PORT` / `REFTRIX_*` preserved
 *
 * **Sensitivity check semantics**: The SSOT `AUDIT_SENSITIVE_KEYS` set
 * contains exact literal keys plus the commonly-used variants. For Node.js
 * environment-variable redaction we additionally apply a case-insensitive
 * substring match against well-known PII fragments (`password`, `secret`,
 * `token`, `apiKey`, `api_key`, `accessToken`, `access_token`,
 * `refreshToken`, `refresh_token`, `authorization`, `cookie`, `session`,
 * `credential`, `private_key`, `privateKey`, `databaseUrl`, `database_url`).
 * The substring sensitivity expansion is JUSTIFIED here because env-var
 * conventions (e.g., `MY_DATABASE_URL`, `OPENAI_API_KEY`, `STRIPE_SECRET_KEY`)
 * embed PII fragments in concatenated keys. Without expansion, only literal
 * `apiKey` / `api_key` would be caught, leaking `MY_API_KEY`. The set itself
 * remains SSOT-imported; only the matching predicate is expanded.
 */
export function sanitizeEnv(env: Record<string, string | undefined>): Record<string, string> {
  if (!env || typeof env !== "object") return {};
  const result: Record<string, string> = {};
  for (const [key, value] of Object.entries(env)) {
    if (value === undefined) continue;
    if (isSensitiveEnvKey(key)) {
      result[key] = REDACTED_VALUE;
    } else {
      // Defense-in-depth: also strip embedded connection URLs from
      // ostensibly-safe env values (e.g., `PATH` contains nothing sensitive
      // but a third-party tool could surface a connection string).
      result[key] = stripConnectionUrls(value);
    }
  }
  return result;
}

/**
 * Test whether an env var name matches the SSOT sensitive-key allowlist.
 * Combines exact-set membership with case-insensitive substring match for
 * common PII fragments embedded in concatenated env names (e.g.,
 * `MY_DATABASE_URL`, `STRIPE_SECRET_KEY`).
 */
function isSensitiveEnvKey(key: string): boolean {
  if (AUDIT_SENSITIVE_KEYS.has(key)) return true;
  const lower = key.toLowerCase();
  for (const sensitiveKey of AUDIT_SENSITIVE_KEYS) {
    if (lower.includes(sensitiveKey.toLowerCase())) return true;
  }
  // Additional well-known fragments not in AUDIT_SENSITIVE_KEYS but
  // semantically equivalent (database URL is the most prominent example —
  // not in the audit-log SSOT because audit_logs.details rarely carries
  // raw env values, but env redaction MUST cover it).
  if (
    lower.includes("database_url") ||
    lower.includes("databaseurl") ||
    lower.includes("redis_url") ||
    lower.includes("redisurl")
  ) {
    return true;
  }
  return false;
}

/** Strip embedded connection URLs (postgres:// / redis:// / etc.) from a value. */
export function stripConnectionUrls(value: string): string {
  if (typeof value !== "string" || value.length === 0) return value;
  CONNECTION_URL_REGEX.lastIndex = 0;
  if (!CONNECTION_URL_REGEX.test(value)) return value;
  CONNECTION_URL_REGEX.lastIndex = 0;
  return value.replace(CONNECTION_URL_REGEX, REDACTED_URL);
}

/**
 * Normalise a JS stack frame file path. Repo-internal paths are converted
 * to relative form (`apps/mcp-server/...`); external paths are redacted.
 *
 * Per V1 §7.1 unit test #4 + Δ2 #4:
 *   - `/home/user/.../Reftrix/apps/mcp-server/src/x.ts` →
 *     `apps/mcp-server/src/x.ts`
 *   - `/home/user/.../secret.json` (outside repo) → `[REDACTED-NON-REPO-PATH]`
 */
export function normaliseStackFramePath(framePath: string): string {
  if (typeof framePath !== "string" || framePath.length === 0) return framePath;
  // Built-in modules (no path separator) — pass through.
  if (!framePath.includes("/") && !framePath.includes("\\")) return framePath;
  let resolved: string;
  try {
    resolved = path.resolve(framePath);
  } catch {
    return REDACTED_NON_REPO_PATH;
  }
  const repoRoot = resolveRepoRoot();
  if (resolved.startsWith(repoRoot + path.sep) || resolved === repoRoot) {
    const relative = path.relative(repoRoot, resolved);
    // Always use POSIX-style separators in the sanitised output for
    // platform-independent assertions.
    return relative.split(path.sep).join("/");
  }
  return REDACTED_NON_REPO_PATH;
}

/**
 * Walk a string field for embedded URLs (`https?://`) and connection URLs
 * (`postgres://`, `redis://`, etc.). Used by the heap-string defense (Δ2 #5).
 */
export function sanitizeHeapString(value: string): string {
  if (typeof value !== "string" || value.length === 0) return value;
  let result = stripConnectionUrls(value);
  URL_REGEX.lastIndex = 0;
  if (URL_REGEX.test(result)) {
    URL_REGEX.lastIndex = 0;
    result = result.replace(URL_REGEX, REDACTED_URL);
  }
  UUID_REGEX.lastIndex = 0;
  if (UUID_REGEX.test(result)) {
    UUID_REGEX.lastIndex = 0;
    result = result.replace(UUID_REGEX, REDACTED_UUID);
  }
  return result;
}

// ============================================================================
// Main sanitiser entry point
// ============================================================================

/**
 * Sanitise a raw Node.js `process.report` object. Returns a new object; does
 * not mutate input. Returns a {@link CrashReportSanitizationResult} with
 * timing + observability metadata for the audit emit downstream.
 *
 * **Fail-open contract** (Δ2 #6): if any step throws, the original report is
 * returned with `sanitizationApplied=false` and a SLO marker is logged.
 * The downstream audit emit then triggers L1.5 SLO_MARKER and Δ5 Metric A
 * (GDPR Art.33 escalate gate via L3 CRIT).
 */
export function sanitizeReport(rawReport: unknown): CrashReportSanitizationResult {
  const startTime = Date.now();
  // Defensive copy + sanitisation in a single try-block. The fail-open
  // contract requires we return the ORIGINAL report (untouched) if any
  // throw occurs, so we keep `rawReport` aside and operate on a clone.
  try {
    if (rawReport === null || typeof rawReport !== "object") {
      // Non-object input — pass through but mark sanitised (nothing to redact).
      return {
        report: rawReport,
        sanitizationApplied: true,
        sanitizationDurationMs: Date.now() - startTime,
        jsStackTopFrame: null,
        nativeStackTopSymbol: null,
      };
    }
    const cloned = JSON.parse(JSON.stringify(rawReport)) as Record<string, unknown>;
    const sanitisedReport = sanitiseReportInternal(cloned);
    const jsStackTopFrame = extractJsStackTopFrame(sanitisedReport);
    const nativeStackTopSymbol = extractNativeStackTopSymbol(sanitisedReport);
    return {
      report: sanitisedReport,
      sanitizationApplied: true,
      sanitizationDurationMs: Date.now() - startTime,
      jsStackTopFrame,
      nativeStackTopSymbol,
    };
  } catch (error) {
    // Fail-open: emit SLO marker, return original report, downstream audit
    // emit will set sanitizationApplied=false → Δ5 Metric A trigger.
    logger.warn(SLO_MARKER_SANITIZE_FAILED, {
      errorMessage: error instanceof Error ? error.message : "unknown",
    });
    return {
      report: rawReport,
      sanitizationApplied: false,
      sanitizationDurationMs: Date.now() - startTime,
      jsStackTopFrame: null,
      nativeStackTopSymbol: null,
    };
  }
}

/**
 * Recursive sanitisation walker for the cloned report tree. Internal — must
 * stay total over arbitrary `process.report` shape (Node version drift
 * tolerant). Keys present in `process.report` v12+ stable shape:
 *   - `header.commandLine` (argv array)
 *   - `environmentVariables` (object)
 *   - `javascriptStack.stack` (array of frame strings)
 *   - `nativeStack` (array of symbol strings)
 *   - `javascriptHeap` (object containing arbitrary heap fields)
 *   - `libuv` / `workers` / `userLimits` / `sharedObjects` (less PII-prone)
 *
 * For unknown keys we recursively walk and apply heap-string sanitisation to
 * any string leaf. This is defensive against future Node versions adding new
 * keys (R4 mitigation).
 *
 * **Wave 4 SRP refactor (TDA M-1 c, 2026-05-11)**: split the inline 5-section
 * body into 5 named sub-functions, each with CC ≤ 5, matching the Wave 1
 * T3-Vision precedent. Behaviour-preserving — 39 sanitizer + 7 PII safety
 * unit tests + 1 PII leak fail-closed standing all continue to pass post-
 * refactor. The orchestrator below now has CC = 1 (5 linear delegations).
 *
 * @see Wave 4 Finding Registry TDA M-1 c (CC>10 SRP refactor)
 */
function sanitiseReportInternal(obj: Record<string, unknown>): Record<string, unknown> {
  // Each sub-function is a no-op when its section is missing / mistyped, so
  // the orchestrator can stay linear (CC = 1) over the 5 sections.
  sanitiseHeader(obj);
  sanitiseEnvironmentVariables(obj);
  sanitiseJavascriptStack(obj);
  sanitiseNativeStack(obj);
  sanitiseJavascriptHeap(obj);
  return obj;
}

/**
 * Section 1 — `header.commandLine` argv + `header.cwd` path normalisation.
 *
 * No-op when `obj.header` is absent or not an object. Mutates `obj.header`
 * in place when present.
 *
 * Cyclomatic complexity ≤ 5 (3 type guards + linear assignments).
 */
function sanitiseHeader(obj: Record<string, unknown>): void {
  if (!obj.header || typeof obj.header !== "object") return;
  const header = obj.header as Record<string, unknown>;
  if (Array.isArray(header.commandLine)) {
    header.commandLine = sanitizeArgv(header.commandLine as readonly string[]);
  }
  // `cwd` / `host` may surface usernames — redact if outside repo root.
  if (typeof header.cwd === "string") {
    header.cwd = normaliseStackFramePath(header.cwd);
  }
}

/**
 * Section 2 — `environmentVariables` AUDIT_SENSITIVE_KEYS SSOT + case-
 * insensitive substring match.
 *
 * Cyclomatic complexity ≤ 5 (1 type guard + 1 assignment).
 */
function sanitiseEnvironmentVariables(obj: Record<string, unknown>): void {
  if (!obj.environmentVariables || typeof obj.environmentVariables !== "object") return;
  obj.environmentVariables = sanitizeEnv(
    obj.environmentVariables as Record<string, string | undefined>
  );
}

/**
 * Section 3 — `javascriptStack.stack` frame array + `javascriptStack.message`
 * heap-string sanitisation.
 *
 * Cyclomatic complexity ≤ 5 (3 type guards + 1 map callback with 1 guard).
 */
function sanitiseJavascriptStack(obj: Record<string, unknown>): void {
  if (!obj.javascriptStack || typeof obj.javascriptStack !== "object") return;
  const jsStack = obj.javascriptStack as Record<string, unknown>;
  if (Array.isArray(jsStack.stack)) {
    jsStack.stack = (jsStack.stack as unknown[]).map((frame) => {
      if (typeof frame !== "string") return frame;
      return sanitiseStackFrameLine(frame);
    });
  }
  if (typeof jsStack.message === "string") {
    jsStack.message = sanitizeHeapString(jsStack.message);
  }
}

/**
 * Section 4 — `nativeStack` symbol stripping (native internal prefix + file
 * path normalisation).
 *
 * Map callback CC ≤ 5 (3 guard branches + 1 fall-through return). The
 * outer function delegates entirely to the map.
 */
function sanitiseNativeStack(obj: Record<string, unknown>): void {
  if (!Array.isArray(obj.nativeStack)) return;
  obj.nativeStack = (obj.nativeStack as unknown[]).map((entry) => sanitiseNativeStackEntry(entry));
}

/**
 * Section 4 helper — sanitise a single `nativeStack` entry.
 *
 * Entries may be: (a) plain symbol strings, (b) `{ symbol: string }` objects,
 * or (c) any other shape (passed through unchanged).
 *
 * Cyclomatic complexity ≤ 5 (3 branches + 1 default).
 */
function sanitiseNativeStackEntry(entry: unknown): unknown {
  if (typeof entry === "string") return stripNonPublicNativeSymbols(entry);
  if (entry && typeof entry === "object") {
    const e = entry as Record<string, unknown>;
    if (typeof e.symbol === "string") e.symbol = stripNonPublicNativeSymbols(e.symbol);
    return e;
  }
  return entry;
}

/**
 * Section 5 — `javascriptHeap` heap-string PII strip (Δ2 #5).
 *
 * Cyclomatic complexity ≤ 5 (1 type guard + 1 assignment).
 */
function sanitiseJavascriptHeap(obj: Record<string, unknown>): void {
  if (!obj.javascriptHeap || typeof obj.javascriptHeap !== "object") return;
  obj.javascriptHeap = sanitiseHeapObject(obj.javascriptHeap as Record<string, unknown>);
}

/**
 * Sanitise a JS stack frame line. Node.js stack frames have the shape:
 *   `at FunctionName (/path/to/file.ts:line:col)`
 * We extract the path between the parens and run it through
 * {@link normaliseStackFramePath}. If no parens are present, fall back to
 * heap-string sanitisation on the whole line.
 */
function sanitiseStackFrameLine(frame: string): string {
  const parenMatch = frame.match(/^(.*?\()(.+?)(:\d+:\d+\)?)$/);
  if (parenMatch !== null && parenMatch.length >= 4) {
    const prefix = parenMatch[1] ?? "";
    const filePath = parenMatch[2] ?? "";
    const suffix = parenMatch[3] ?? "";
    return prefix + normaliseStackFramePath(filePath) + suffix;
  }
  // No parens — pass through heap-string sanitisation (URL + UUID redaction).
  return sanitizeHeapString(frame);
}

/**
 * Recursively sanitise a heap object: for every string leaf, apply
 * {@link sanitizeHeapString}; for every nested object, recurse; for every
 * key matching `AUDIT_SENSITIVE_KEYS`, redact to `[REDACTED]`.
 *
 * **Wave 4 SRP refactor (TDA V1-04 c, 2026-05-11)**: split the inline body
 * (previously CC=12) into 3 named sub-functions, each with CC ≤ 5:
 *   - {@link sanitiseHeapObject} (orchestrator): CC = 3 (depth guard + for + 1 redacted-key branch)
 *   - {@link sanitiseHeapValue}: CC = 5 (string / array / object / primitive dispatch)
 *   - {@link sanitiseHeapArrayItem}: CC = 4 (string / object / primitive dispatch)
 *
 * Behaviour-preserving — 39 sanitizer + 7 PII safety unit tests + 1 PII leak
 * fail-closed standing regression all continue to pass post-refactor.
 *
 * @see Wave 4 Finding Registry TDA V1-04 c (sanitiseHeapObject CC=12 refactor)
 */
function sanitiseHeapObject(
  obj: Record<string, unknown>,
  depth: number = 0
): Record<string, unknown> {
  // Bounded recursion (defense against malformed circular refs after clone).
  if (depth > 64) return obj;
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(obj)) {
    if (AUDIT_SENSITIVE_KEYS.has(key) || isSensitiveEnvKey(key)) {
      result[key] = REDACTED_VALUE;
      continue;
    }
    result[key] = sanitiseHeapValue(value, depth);
  }
  return result;
}

/**
 * Dispatch a single heap value to the appropriate sanitiser based on its
 * runtime type. Delegate for {@link sanitiseHeapObject}'s value branch.
 *
 * Cyclomatic complexity ≤ 5 (string / array / object / primitive 4-way
 * dispatch + 1 null guard).
 */
function sanitiseHeapValue(value: unknown, depth: number): unknown {
  if (typeof value === "string") {
    return sanitizeHeapString(value);
  }
  if (Array.isArray(value)) {
    return value.map((v) => sanitiseHeapArrayItem(v, depth));
  }
  if (value !== null && typeof value === "object") {
    return sanitiseHeapObject(value as Record<string, unknown>, depth + 1);
  }
  return value;
}

/**
 * Dispatch a single heap array element to the appropriate sanitiser.
 *
 * Cyclomatic complexity ≤ 5 (string / object / primitive 3-way dispatch +
 * 1 null guard).
 */
function sanitiseHeapArrayItem(item: unknown, depth: number): unknown {
  if (typeof item === "string") {
    return sanitizeHeapString(item);
  }
  if (item !== null && typeof item === "object") {
    return sanitiseHeapObject(item as Record<string, unknown>, depth + 1);
  }
  return item;
}

/** Extract the top JS frame for audit emit `details.jsStackTopFrame`. */
function extractJsStackTopFrame(report: Record<string, unknown>): string | null {
  const jsStack = report.javascriptStack as Record<string, unknown> | undefined;
  if (!jsStack || typeof jsStack !== "object") return null;
  const stack = jsStack.stack;
  if (!Array.isArray(stack) || stack.length === 0) return null;
  const top = stack[0];
  return typeof top === "string" ? top : null;
}

/** Extract the top native symbol for audit emit `details.nativeStackTopSymbol`. */
function extractNativeStackTopSymbol(report: Record<string, unknown>): string | null {
  const nativeStack = report.nativeStack;
  if (!Array.isArray(nativeStack) || nativeStack.length === 0) return null;
  const top = nativeStack[0];
  if (typeof top === "string") return top;
  if (top !== null && typeof top === "object") {
    const symbol = (top as Record<string, unknown>).symbol;
    return typeof symbol === "string" ? symbol : null;
  }
  return null;
}

// ============================================================================
// Truncated report ID generation (Δ11 pid leakage refactor)
// ============================================================================

/**
 * Generate a truncated report ID for use in audit emit `details.truncatedReportId`
 * and as the targetId for audit_logs PII-safety binding. Per Δ11, the format
 * is `report.<truncatedTs>.<seqOnly>` where:
 *   - `truncatedTs` = `floor(unix_timestamp_seconds / 60) * 60` (1-min bucket)
 *   - `seqOnly` = process-local monotonic sequence (no pid)
 *
 * The targetId is then PII-truncated to `AUDIT_LOG_CONSTANTS.TARGET_ID_TRUNCATE_LENGTH`
 * via the SSOT `truncateAuditTargetId` helper.
 */
let processLocalSeq = 0;
export function generateTruncatedReportId(now: Date = new Date()): string {
  const unixSec = Math.floor(now.getTime() / 1000);
  const bucketSec = Math.floor(unixSec / 60) * 60;
  const seq = ++processLocalSeq;
  return `report.${bucketSec}.${seq}`;
}

/** Test-only: reset process-local sequence so deterministic IDs can be asserted. */
export function resetSequenceForTesting(): void {
  processLocalSeq = 0;
}

/**
 * Build the audit-log-safe target ID for a crash report. Combines
 * {@link generateTruncatedReportId} with SSOT
 * {@link truncateAuditTargetId} (= 8 chars + "..." per
 * `AUDIT_LOG_CONSTANTS.TARGET_ID_TRUNCATE_LENGTH`).
 */
export function buildAuditTargetIdForReport(truncatedReportId: string): string | null {
  return truncateAuditTargetId(truncatedReportId);
}
